sudo: required
language: cpp
compiler: g++
addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
        packages:
            - cmake-data
            - cmake
            - g++-8
os: linux
before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
install:
    - mkdir build && cd build && cmake .. && make logger_tests; 
script:
    - ls
    - cd ../bin && ./logger_tests
notifications:
    email:true
branches:
    only:
        - develop
        - master
